import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      type: i.string().optional(),
      acceptedTermsVersion: i.string().optional(),
      acceptedTermsAt: i.number().optional(),
      acceptedOrganizerTermsVersion: i.string().optional(),
      acceptedOrganizerTermsAt: i.number().optional(),
      acceptedPrivacyVersion: i.string().optional(),
      acceptedPrivacyAt: i.number().optional(),
    }),
    concerts: i.entity({
      name: i.string(),
      slug: i.string().unique().indexed(),
      date: i.string(),
      venue: i.string().optional(),
      venueMapUrl: i.string().optional(),
      description: i.string().optional(),
      status: i.string().indexed(),
      scannerPin: i.string().optional(),
      flyerUrl: i.string().optional(),
      flyerPath: i.string().optional(),
      logoUrl: i.string().optional(),
      logoPath: i.string().optional(),
      primaryColor: i.string().optional(),
      lastOrderSeq: i.number().optional().indexed(),
      orderNumberPrefix: i.string().optional().unique().indexed(),
      organizerEmail: i.string().indexed(),
      defaultLanguage: i.string().optional(),
      isDemo: i.boolean().optional().indexed(),
      createdAt: i.number().indexed(),
    }),
    ticketTypes: i.entity({
      name: i.string(),
      price: i.number(),
      quantity: i.number(),
      description: i.string().optional(),
      visibility: i.string().optional(),
      hideAvailability: i.boolean().optional(),
      feePercent: i.number().optional(),
      feeFixed: i.number().optional(),
      lastQueuePosition: i.number().optional().indexed(),
      createdAt: i.number().indexed(),
    }),
    orders: i.entity({
      firstName: i.string(),
      lastName: i.string(),
      email: i.string().indexed(),
      cedula: i.string().indexed(),
      paymentMethod: i.string(),
      promoter: i.string().optional(),
      customFieldValues: i.string().optional(),
      status: i.string().indexed(),
      paymentProofPath: i.string().optional(),
      proofReferenceNumber: i.string().optional(),
      visited: i.boolean().indexed(),
      visitedAt: i.number().optional().indexed(),
      couponCode: i.string().optional(),
      discountAmount: i.number().optional(),
      paymentMethodDiscount: i.number().optional(),
      phaseId: i.string().optional(),
      orderNumber: i.string().optional().unique().indexed(),
      purchaseGroupId: i.string().optional().indexed(),
      purchaseRate: i.number().optional(),
      purchaseRateCurrency: i.string().optional(),
      purchaseAmountBs: i.number().optional(),
      priceSnapshot: i.number().optional(),
      feePercentSnapshot: i.number().optional(),
      feeFixedSnapshot: i.number().optional(),
      feeAmountSnapshot: i.number().optional(),
      totalSnapshot: i.number().optional(),
      platformFeePercentSnapshot: i.number().optional(),
      platformFeeFixedSnapshot: i.number().optional(),
      platformFeeAmountSnapshot: i.number().optional(),
      acceptedTermsVersion: i.string().optional(),
      acceptedPrivacyVersion: i.string().optional(),
      language: i.string().optional(),
      createdAt: i.number().indexed(),
    }),
    paymentMethods: i.entity({
      type: i.string().indexed(),
      name: i.string(),
      instructions: i.string().optional(),
      convertCurrency: i.string().optional(),
      requireScreenshot: i.boolean().optional(),
      requireReferenceNumber: i.boolean().optional(),
      showConversionDetail: i.boolean().optional(),
      customRate: i.number().optional(),
      zelleEmail: i.string().optional(),
      zelleName: i.string().optional(),
      pmCedula: i.string().optional(),
      pmPhone: i.string().optional(),
      pmBank: i.string().optional(),
      discountType: i.string().optional(),
      discountValue: i.number().optional(),
      createdAt: i.number().indexed(),
    }),
    customFields: i.entity({
      label: i.string(),
      fieldType: i.string(),
      required: i.boolean(),
      options: i.string().optional(),
      sortOrder: i.number().indexed(),
      createdAt: i.number().indexed(),
    }),
    exchangeRates: i.entity({
      currency: i.string().indexed(),
      rate: i.number(),
      fetchedAt: i.number().indexed(),
    }),
    ticketPhases: i.entity({
      name: i.string(),
      price: i.number(),
      quantity: i.number(),
      endDate: i.string().optional().indexed(),
      sortOrder: i.number().indexed(),
      createdAt: i.number().indexed(),
    }),
    coupons: i.entity({
      code: i.string().unique().indexed(),
      discountType: i.string(),
      discountValue: i.number(),
      maxUses: i.number().optional(),
      active: i.boolean().indexed(),
      createdAt: i.number().indexed(),
    }),
    reservations: i.entity({
      quantity: i.number(),
      expiresAt: i.number().indexed(),
      phaseId: i.string().optional(),
      createdAt: i.number().indexed(),
    }),
    queueEntries: i.entity({
      sessionId: i.string().indexed(),
      status: i.string().indexed(),
      position: i.number().indexed(),
      quantity: i.number(),
      admittedAt: i.number().optional().indexed(),
      expiresAt: i.number().indexed(),
      createdAt: i.number().indexed(),
    }),
    messages: i.entity({
      firstName: i.string(),
      lastName: i.string(),
      email: i.string().indexed(),
      subject: i.string(),
      body: i.string(),
      status: i.string().indexed(),
      adminReply: i.string().optional(),
      repliedAt: i.number().optional().indexed(),
      language: i.string().optional(),
      createdAt: i.number().indexed(),
    }),
    organizerBalances: i.entity({
      email: i.string().unique().indexed(),
      balance: i.number(),
      currency: i.string(),
      updatedAt: i.number().indexed(),
    }),
    balanceTransactions: i.entity({
      type: i.string().indexed(),
      amount: i.number(),
      balanceBefore: i.number(),
      balanceAfter: i.number(),
      description: i.string(),
      orderId: i.string().optional().indexed(),
      concertId: i.string().optional().indexed(),
      createdAt: i.number().indexed(),
    }),
    platformFeeConfigs: i.entity({
      feePercent: i.number(),
      feeFixed: i.number(),
      billingMode: i.string().indexed(),
      updatedAt: i.number().indexed(),
    }),
    emailSuppressions: i.entity({
      email: i.string().unique().indexed(),
      reason: i.string().indexed(),
      source: i.string(),
      detail: i.string().optional(),
      createdAt: i.number().indexed(),
    }),
    credentials: i.entity({
      passwordHash: i.string(),
      createdAt: i.number().indexed(),
    }),
    eventCollaborators: i.entity({
      email: i.string().indexed(),
      invitedAt: i.number().indexed(),
      invitedByEmail: i.string(),
    }),
    broadcasts: i.entity({
      subject: i.string(),
      body: i.string(),
      filtersJson: i.string(),
      recipientCount: i.number().indexed(),
      sentCount: i.number(),
      failedCount: i.number(),
      suppressedCount: i.number(),
      status: i.string().indexed(),
      createdByEmail: i.string().indexed(),
      createdAt: i.number().indexed(),
      completedAt: i.number().optional().indexed(),
      failedEmailsJson: i.string().optional(),
      processingState: i.string().optional().indexed(),
      lastWorkerAt: i.number().optional().indexed(),
    }),
    broadcastDeliveries: i.entity({
      email: i.string().indexed(),
      emailDisplay: i.string(),
      firstName: i.string(),
      lastName: i.string(),
      ticketTypeName: i.string(),
      paymentMethod: i.string(),
      orderStatus: i.string(),
      language: i.string().optional(),
      deliveryStatus: i.string().indexed(),
      attempts: i.number().indexed(),
      lastTriedAt: i.number().optional().indexed(),
      sentAt: i.number().optional().indexed(),
      failedAt: i.number().optional().indexed(),
      reason: i.string().optional(),
      claimToken: i.string().optional().indexed(),
      claimedAt: i.number().optional().indexed(),
      createdAt: i.number().indexed(),
    }),
    guestListEvents: i.entity({
      name: i.string(),
      slug: i.string().unique().indexed(),
      date: i.string(),
      venue: i.string().optional(),
      venueMapUrl: i.string().optional(),
      description: i.string().optional(),
      status: i.string().indexed(),
      flyerUrl: i.string().optional(),
      flyerPath: i.string().optional(),
      logoUrl: i.string().optional(),
      logoPath: i.string().optional(),
      primaryColor: i.string().optional(),
      organizerEmail: i.string().indexed(),
      defaultLanguage: i.string().optional(),
      scannerPin: i.string().optional(),
      defaultPrice: i.number(),
      capacity: i.number().optional(),
      lastOrderSeq: i.number().optional().indexed(),
      orderNumberPrefix: i.string().optional().indexed(),
      createdAt: i.number().indexed(),
    }),
    guestListEntries: i.entity({
      email: i.string().optional().indexed(),
      cedula: i.string().optional().indexed(),
      firstName: i.string().optional(),
      lastName: i.string().optional(),
      priceOverride: i.number().optional(),
      status: i.string().indexed(),
      inviteToken: i.string().unique().indexed(),
      inviteSentAt: i.number().optional().indexed(),
      registeredAt: i.number().optional().indexed(),
      createdAt: i.number().indexed(),
    }),
    guestListOrders: i.entity({
      firstName: i.string(),
      lastName: i.string(),
      email: i.string().indexed(),
      cedula: i.string().indexed(),
      status: i.string().indexed(),
      visited: i.boolean().indexed(),
      visitedAt: i.number().optional().indexed(),
      paymentMethod: i.string().optional(),
      paymentMethodId: i.string().optional().indexed(),
      paymentProofPath: i.string().optional(),
      proofReferenceNumber: i.string().optional(),
      pricePaid: i.number(),
      customFieldValues: i.string().optional(),
      orderNumber: i.string().optional().unique().indexed(),
      orderToken: i.string().unique().indexed(),
      language: i.string().optional(),
      createdAt: i.number().indexed(),
    }),
    guestListPaymentMethods: i.entity({
      type: i.string().indexed(),
      name: i.string(),
      instructions: i.string().optional(),
      convertCurrency: i.string().optional(),
      requireScreenshot: i.boolean().optional(),
      requireReferenceNumber: i.boolean().optional(),
      showConversionDetail: i.boolean().optional(),
      customRate: i.number().optional(),
      zelleEmail: i.string().optional(),
      zelleName: i.string().optional(),
      pmCedula: i.string().optional(),
      pmPhone: i.string().optional(),
      pmBank: i.string().optional(),
      discountType: i.string().optional(),
      discountValue: i.number().optional(),
      sortOrder: i.number().indexed(),
      createdAt: i.number().indexed(),
    }),
    guestListCustomFields: i.entity({
      label: i.string(),
      fieldType: i.string(),
      required: i.boolean(),
      options: i.string().optional(),
      sortOrder: i.number().indexed(),
      createdAt: i.number().indexed(),
    }),
    guestListCollaborators: i.entity({
      email: i.string().indexed(),
      invitedAt: i.number().indexed(),
      invitedByEmail: i.string(),
    }),
    guestListTicketTypes: i.entity({
      name: i.string(),
      price: i.number(),
      quantity: i.number().optional(),
      description: i.string().optional(),
      sortOrder: i.number().indexed(),
      createdAt: i.number().indexed(),
    }),
  },
  links: {
    concertTicketTypes: {
      forward: {
        on: "ticketTypes",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "many",
        label: "ticketTypes",
      },
    },
    ticketTypeOrders: {
      forward: {
        on: "orders",
        has: "one",
        label: "ticketType",
        onDelete: "cascade",
      },
      reverse: {
        on: "ticketTypes",
        has: "many",
        label: "orders",
      },
    },
    concertPaymentMethods: {
      forward: {
        on: "paymentMethods",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "many",
        label: "paymentMethods",
      },
    },
    concertCustomFields: {
      forward: {
        on: "customFields",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "many",
        label: "customFields",
      },
    },
    ticketTypePhases: {
      forward: {
        on: "ticketPhases",
        has: "one",
        label: "ticketType",
        onDelete: "cascade",
      },
      reverse: {
        on: "ticketTypes",
        has: "many",
        label: "phases",
      },
    },
    concertCoupons: {
      forward: {
        on: "coupons",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "many",
        label: "coupons",
      },
    },
    ticketTypeReservations: {
      forward: {
        on: "reservations",
        has: "one",
        label: "ticketType",
        onDelete: "cascade",
      },
      reverse: {
        on: "ticketTypes",
        has: "many",
        label: "reservations",
      },
    },
    ticketTypeQueueEntries: {
      forward: {
        on: "queueEntries",
        has: "one",
        label: "ticketType",
        onDelete: "cascade",
      },
      reverse: {
        on: "ticketTypes",
        has: "many",
        label: "queueEntries",
      },
    },
    concertMessages: {
      forward: {
        on: "messages",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "many",
        label: "messages",
      },
    },
    balanceTransactionBalance: {
      forward: {
        on: "balanceTransactions",
        has: "one",
        label: "organizerBalance",
      },
      reverse: {
        on: "organizerBalances",
        has: "many",
        label: "transactions",
      },
    },
    concertPlatformFee: {
      forward: {
        on: "platformFeeConfigs",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "one",
        label: "platformFeeConfig",
      },
    },
    userCredentials: {
      forward: {
        on: "credentials",
        has: "one",
        label: "user",
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "one",
        label: "credentials",
      },
    },
    concertCollaborators: {
      forward: {
        on: "eventCollaborators",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "many",
        label: "collaborators",
      },
    },
    concertBroadcasts: {
      forward: {
        on: "broadcasts",
        has: "one",
        label: "concert",
        onDelete: "cascade",
      },
      reverse: {
        on: "concerts",
        has: "many",
        label: "broadcasts",
      },
    },
    broadcastDeliveryItems: {
      forward: {
        on: "broadcastDeliveries",
        has: "one",
        label: "broadcast",
        onDelete: "cascade",
      },
      reverse: {
        on: "broadcasts",
        has: "many",
        label: "deliveries",
      },
    },
    guestListEntriesEvent: {
      forward: {
        on: "guestListEntries",
        has: "one",
        label: "event",
        onDelete: "cascade",
      },
      reverse: {
        on: "guestListEvents",
        has: "many",
        label: "entries",
      },
    },
    guestListOrderEntry: {
      forward: {
        on: "guestListOrders",
        has: "one",
        label: "entry",
        onDelete: "cascade",
      },
      reverse: {
        on: "guestListEntries",
        has: "one",
        label: "order",
      },
    },
    guestListPaymentMethodEvent: {
      forward: {
        on: "guestListPaymentMethods",
        has: "one",
        label: "event",
        onDelete: "cascade",
      },
      reverse: {
        on: "guestListEvents",
        has: "many",
        label: "paymentMethods",
      },
    },
    guestListCustomFieldsEvent: {
      forward: {
        on: "guestListCustomFields",
        has: "one",
        label: "event",
        onDelete: "cascade",
      },
      reverse: {
        on: "guestListEvents",
        has: "many",
        label: "customFields",
      },
    },
    guestListCollaboratorsEvent: {
      forward: {
        on: "guestListCollaborators",
        has: "one",
        label: "event",
        onDelete: "cascade",
      },
      reverse: {
        on: "guestListEvents",
        has: "many",
        label: "collaborators",
      },
    },
    guestListTicketTypesEvent: {
      forward: {
        on: "guestListTicketTypes",
        has: "one",
        label: "event",
        onDelete: "cascade",
      },
      reverse: {
        on: "guestListEvents",
        has: "many",
        label: "ticketTypes",
      },
    },
    guestListEntriesTicketType: {
      forward: {
        on: "guestListEntries",
        has: "one",
        label: "ticketType",
      },
      reverse: {
        on: "guestListTicketTypes",
        has: "many",
        label: "entries",
      },
    },
    guestListOrdersTicketType: {
      forward: {
        on: "guestListOrders",
        has: "one",
        label: "ticketType",
      },
      reverse: {
        on: "guestListTicketTypes",
        has: "many",
        label: "orders",
      },
    },
  },
  rooms: {
    eventPage: {
      presence: i.entity({
        joinedAt: i.number(),
      }),
    },
  },
});

type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
